#!/bin/bash -e
# vim: set tabstop=8 shiftwidth=4 softtabstop=4 expandtab smarttab colorcolumn=80:
#
# Copyright (c) 2017 Red Hat, Inc.
# Author: Nathaniel McCallum <npmccallum@redhat.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

[ $# -eq 1 ] && [ "$1" == "--summary" ] && exit 2

read -r -d . hdr

if [ "$(jose fmt -q "$hdr" -SyOg clevis -g pin -u-)" != "keyscript" ]; then
    echo "JWE pin mismatch!" >&2
    exit 1
fi

keyscript=$(jose fmt -q "$hdr" -SyOg clevis -g cfg -g keyscript -u-)
key=$(exec $keyscript)
jwk=$(jose jwk gen -i '{"alg":"A256GCM"}' | jose fmt -j- -O -q $key -Ss k -Uo-)

exec jose jwe dec -k- -i- < <(echo -n "$jwk$hdr."; /bin/cat)
